name: 'Trigger workflow action with custom input'
description: 'Triggers action on workflow using a custom input'
branding:
  icon: arrow-right-circle
  color: green
inputs:
  token:
    description: 'personal access token'
    required: true
  repository:
    description: 'repository'
    required: true
  workflowId:
    description: 'ID of workflow'
    required: true
  branch:
    description: 'branch'
    required: false
    default: 'main'
  version:
    description: 'required version'
    required: true
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        curl --header 'Authorization: Bearer ${{ inputs.token }}' -X POST https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflowId }}/dispatches -d '{"ref":"${{ inputs.branch }}","inputs":{"tag-name":"${{ inputs.version}}"}'
